#!/bin/csh -f
#------------------------------------------------------------------------------
#
#DESCRIPTION:  This script compiles the C routines necessary to read
#              a CRS HDF file. Paths to the HDF 'include' and 'lib'
#              directories must be defined. This sample script uses
#              environment variables to make these definitions.
#
# The environment variables HDFINC and HDFLIB need to be set.
#   HDFINC - Path to the directory containing the HDF include files.
#   HDFLIB - Path to the directory containing the HDF library.
#
# Example:
#   The following values of HDFINC and HDFLIB were used on an SGI at the 
#   CERES Science Computing Facility at NASA Langley Research Center.
#
#  setenv HDFINC /opt/net/TK5.2.1v1/TOOLKIT/hdf/sgi32/HDF4.1r1/include
#  setenv HDFLIB /opt/net/TK5.2.1v1/TOOLKIT/hdf/sgi32/HDF4.1r1/lib

setenv HDFINC /export/home/hunt/hdf_4.1r2/include
setenv HDFLIB /export/home/hunt/hdf_4.1r2/lib

#
# The C compiler and compiler flags specifications depend on the
#  computer and operating system and, for SGIs, on the object code
#  word size of the installed HDF libraries.  Examples are given for 
#  systems on which the code has been tested.  Additional compile 
#  information is available from 
#    - the NCSA HDF web site at
#
#         http://hdf.ncsa.uiuc.edu/training/compile/
#
#    - the README file in your top level HDF directory, or 
#    - in the directory release_notes/compile.txt in your 
#      HDF installation directory path.
#  
#  Below are the generic statements needed to compile and link this
#  example software:
#
#COMPILER FLAGS -c -I$HDFINC CRS_readHDFfuncs_daacv3.c 
#COMPILER FLAGS -c -I$HDFINC CRS_readhdf_daacv3.c
#COMPILER FLAGS -s -o crs_rd CRS_readHDFfuncs_daacv3.o CRS_readhdf_daacv3.o -L$HDFLIB -lmfhdf -ldf -lz
#
#  where appropriate values are substituted for COMPILER and FLAGS.
#  The values for tested operating systems are:
#
#	computer and
#       operating system	COMPILER	FLAGS
#       -----------------------------------------------------
#	SGI (IRIX 6.2 & 6.4)	cc		-32/-n32/-64*
#	HP (HP-UX 10.10)	c89		none
#       Sun (SunOS 4.1.3)	acc		none
#	Sun (Solaris 2.5)	cc		-Xc
#
#  * The flag setting for the SGI machine is determined by the HDF library
#    object code installed on your system.  One source for this information
#    is to look at the sample C compilation statements in the README file 
#    in your top level HDF directory.  More information about the different
#    object forms is available from the cc man page on SGI systems:
#	man cc
#
#  On SUN Solaris systems an additional library (libnsl.a) must be 
#  included to properly load and execute.  Uncomment the following
#  three lines to create the executable for this read software 
#  package (some modifications for locations of libraries may be needed
#  in these lines).
gcc -c -I$HDFINC CRS_readHDFfuncs_daacv3.c 
gcc -c -I$HDFINC CRS_readhdf_daacv3.c
gcc -o crs_rd CRS_readHDFfuncs_daacv3.o CRS_readhdf_daacv3.o -L$HDFLIB -lmfhdf -ldf -lz -lnsl
#
# Example compile commands for an SGI with HDF libraries in n32 object form:
# Uncomment the following three lines to create the executable for this 
# read software package (some modifications for locations of libraries
# may be needed in these lines).
#cc -n32 -c -I$HDFINC CRS_readHDFfuncs_daacv3.c 
#cc -n32 -c -I$HDFINC CRS_readhdf_daacv3.c
#cc -n32 -s -o crs_rd CRS_readHDFfuncs_daacv3.o CRS_readhdf_daacv3.o -L$HDFLIB -lmfhdf -ldf -ljpeg -lz
