#!/bin/csh -f
#------------------------------------------------------------------------------
#
#DESCRIPTION:  This script compiles the C routines necessary to read
#              an ISCCP-D2like-SSF HDF file. Paths to the HDF 'include' and 'lib'
#              directories must be defined. This sample script uses
#              environment variables to make these definitions.
#
# The environment variables HDFINC and HDFLIB need to be set.
#   HDFINC - Path to the directory containing the HDF include files.
#   HDFLIB - Path to the directory containing the HDF library.
#
# Example:
#   The following values of HDFINC and HDFLIB were used on an SGI at the 
#   CERES Science Computing Facility at NASA Langley Research Center.
#
#   Modify these two lines to the correct path of the location of your
#   HDF include directory and your lib directory.
#
#   setenv HDFINC /fs1/HDF4.1r5/irix_n32/include
#   setenv HDFLIB /fs1/HDF4.1r5/irix_n32/lib
#
#   For a Unix Sun system with Solaris 2.8 on the system, use the 
#   following set up.
   setenv HDFINC /fs1/HDF4.1r5/solaris8_32/include
   setenv HDFLIB /fs1/HDF4.1r5/solaris8_32/lib
#
#  The C compiler and compiler flags specifications depend on the
#  computer and operating system and, for SGIs, on the object code
#  word size of the installed HDF libraries.  Examples are given for 
#  systems on which the code has been tested.  Additional compile 
#  information is available from 
#    - the NCSA HDF web site at
#         http://hdf.ncsa.uiuc.edu/
#
#    - the README file in your top level HDF directory, or 
#    - in the directory release_notes/compile.txt in your 
#      HDF installation directory path.
#  
#  Below are the generic statements needed to compile and link this
#  example software:
#
#COMPILER FLAGS -c -I$HDFINC ISCCP-D2like_readHDFfuncs.c 
#COMPILER FLAGS -c -I$HDFINC ISCCP-D2like_readhdf.c
#COMPILER FLAGS -s -o ISCCP-D2like_rd ISCCP-D2like_readHDFfuncs.o ISCCP-D2like_readhdf.o -L$HDFLIB -lmfhdf -ldf -lz
#
#  where appropriate values are substituted for COMPILER and FLAGS.
#  The values for tested operating systems are:
#
#	computer and
#       operating system	COMPILER	FLAGS
#       -----------------------------------------------------
#	SGI (IRIX 6.2 & 6.4)	cc		-32/-n32/-64*
#	HP (HP-UX 10.10)	c89		none
#       Sun (SunOS 4.1.3)	acc		none
#	Sun (Solaris 2.5)	cc		-Xc
#
#  * The flag setting for the SGI machine is determined by the HDF library
#    object code installed on your system.  One source for this information
#    is to look at the sample C compilation statements in the README file 
#    in your top level HDF directory.  More information about the different
#    object forms is available from the cc man page on SGI systems:
#	man cc
#
#  On SUN Solaris systems an additional library (libnsl.a) must be 
#  included to properly load and execute.  In this case, the third compile 
#  line is
#
# cc -s -o ISCCP-D2like_rd ISCCP-D2like_readHDFfuncs.o ISCCP-D2like_readhdf.o -L$HDFLIB -lmfhdf -ldf -lz -lnsl
#  On SUN Solaris 2.8 system using the GNU compiler, the command is
#  as follows with HDF /HDF4.1r5/solaris8_32/
#
# gcc -c -I$HDFINC ISCCP-D2like_readHDFfuncs.c
# gcc -c -I$HDFINC ISCCP-D2like_readhdf.c
# gcc -s -o ISCCP-D2like_rd ISCCP-D2like_readHDFfuncs.o ISCCP-D2like_readhdf.o -L$HDFLIB -lmfhdf -ldf -lz -ljpeg -lnsl
#
# Example compile commands for an SGI with HDF libraries in n32 object form:
# 
#cc -n32 -w -c -I$HDFINC ISCCP-D2like_readHDFfuncs.c 
#cc -n32 -w -c -I$HDFINC ISCCP-D2like_readhdf.c
#cc -n32 -w -s -o ISCCP-D2like_rd ISCCP-D2like_readHDFfuncs.o ISCCP-D2like_readhdf.o -L$HDFLIB -lmfhdf -ldf -lz -ljpeg
#
# An example of the compile command for an IBM linux cluster with the HDF libraries 
# in m64 object form using C compiler

gcc -c -m64 -mcpu=power6 -DLINUX -D_LP64 -I$HDFINC ISCCP-D2like_readHDFfuncs.c
gcc -c -m64 -mcpu=power6 -DLINUX -D_LP64 -I$HDFINC ISCCP-D2like_readhdf.c
gcc -m64 -o ISCCP-D2like-Mrg_rd ISCCP-D2like_readHDFfuncs.o ISCCP-D2like_readhdf.o -L$HDFLIB -lmfhdf -ldf -ljpeg -lz -lsz -lgcc -ldl -lm


