name: "Quarto Render and Publish to Pages"

on:
  push:
    branches: [ main, quarto/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5 

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: quarto-env
          environment-file: environment.yml

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  # Deploy to GH Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
